In [1]:
import numpy as np
import random

In [3]:
#Creation of numpy array
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
#Difference b/w numpy array and Python list
#Numpy array works in matrics form and list work as single dimension even if you add muultiple list in it 
#Data type Storage 
#In Python list we can store multiple type of data wheras in numpy we can only add values of same data type
#Importing Module
#We dontr need to install any package while using python list wheras to use numpy we have to install it
#Numerical Operations
#List is although capable of Numerical operations but it has less efficiency but numpy array has vast variety of numerical operations with good speed
#Modification Capabilities
#Numpy array have less modification functions as compare to list
#Memory consumption
#List consume more memory as comapre to numpy array

In [13]:
#Time Consumption
# a=%time np.arange(100000)
# b=%time list(range(100000))
# print(a)
# print(b)

In [15]:
#Numpy Array Creation
arr=np.array([5,6,7,8])
print(arr)
print(type(arr))

[5 6 7 8]
<class 'numpy.ndarray'>


In [17]:
l1=[]
for i in range(1,10):
    u=int(input("Enter values in Array"))
    l1.append(u)
arr1=np.array(l1)
print(arr1)

Enter values in Array 67
Enter values in Array 12
Enter values in Array 98
Enter values in Array 11
Enter values in Array 71
Enter values in Array 2
Enter values in Array 19
Enter values in Array 30
Enter values in Array 21


[67 12 98 11 71  2 19 30 21]


In [18]:
#Demensions in array
#1-D Array [1,2,3,4]
#2-D Array [[1,2,3,4]]
#3-D Array [[[1,2,3,4]]
#Higher Dimension Array
print(arr1.ndim)

1


In [19]:
arr2_D=np.array([[1,2,3,4],[5,6,7,8]])
arr2_D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
print(arr2_D.ndim)

2


In [21]:
arr3_D=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
arr3_D

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [22]:
print(arr3_D.ndim)

3


In [29]:
#Multidimensional Array
arn=np.array([1,2,3,4,5],ndmin=6) #ndmin indicates no of dimensions of array
arn1=np.array([[1,2,3,4],[5,6,7,8]],ndmin=5) #ndmin indicates no of dimensions of array
arn
arn1

array([[[[[1, 2, 3, 4],
          [5, 6, 7, 8]]]]])

In [31]:
#Creating Numpy Array using Functions 
#zero array
arr_zero=np.zeros(12)
arr_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
arr_zero1=np.zeros((3,4))
print(arr_zero1)
print(arr_zero1.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [39]:
arr_zero2=np.zeros((3,4,3))
print(arr_zero2)
print(arr_zero2.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3


In [41]:
#ones
arr_ones=np.ones(8)
print(arr_ones)
print(arr_ones.ndim)

[1. 1. 1. 1. 1. 1. 1. 1.]
1


In [44]:
arr_ones2=np.ones((2,4))
print(arr_ones2)
print(arr_ones2.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [45]:
arr_ones2=np.ones((2,4,2))
print(arr_ones2)
print(arr_ones2.ndim)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
3


In [48]:
#Empty Array
arr_empty=np.empty(5)
arr_empty #data of previous array c

array([2.12199579e-314, 9.50654114e-312, 4.70350495e-321, 6.95187041e-310,
       5.33590898e-322])

In [50]:
#Range Array
arr_arrange=np.arange(12)
arr_arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
#Diagonal Matrix
arr_dig=np.eye(3)
arr_dig

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
arr_dig=np.eye(3,5)
arr_dig

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [53]:
#Array with Evenly space
arr_lin=np.linspace(1,10,num=5)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [58]:
arr_lin=np.linspace(1,20,num=10)
print(arr_lin)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [2]:
#Creating Arrays with Random Number
#rand() generate array with value b/w 0 & 1
arr=np.random.rand(8)
print(arr)

[0.53893303 0.22355695 0.56835451 0.92285794 0.47275789 0.50260422
 0.25845422 0.02965327]


In [3]:
arr1=np.random.rand(2,5)
print(arr1)

[[0.4147354  0.3636789  0.104998   0.69742463 0.87758189]
 [0.89331185 0.14466618 0.81923516 0.54255814 0.08932414]]


In [4]:
#randn : generate an array with values close to zero numbers may be positive or negative
arr=np.random.randn(5)
arr

array([-0.56472223, -2.01359311,  0.8636225 ,  0.11159018,  1.13162137])

In [6]:
arr1=np.random.randn(5,4)
arr1

array([[ 0.75651096, -0.49114422, -0.23814868, -1.34201639],
       [-1.3026231 ,  0.43029598,  2.07738518,  1.88754944],
       [-1.49321671, -0.56980674, -0.37022072, -0.79328077],
       [-0.64110959, -0.10001713,  1.48601244, -0.27330604],
       [ 1.27336747, -0.06890072,  1.12415396, -1.82701757]])

In [7]:
#ranf
arr=np.random.ranf(5)
arr

array([0.12586379, 0.87365347, 0.03554485, 0.60596576, 0.72138389])

In [9]:
#randint
arr=np.random.randint(1,10,4) # np.random.randint(min,max,total)
arr

array([3, 3, 1, 5])

In [16]:
#Data Types in Numpy
arr=np.array([1,2,3,4],dtype=np.int8)
print(arr.dtype)


int8


In [11]:
arr=np.array([1.1,5,7,4,9,5,0])
print(arr.dtype)

float64


In [12]:
arr=np.array(["s","a"])
print(arr.dtype)

<U1


In [13]:
arr=np.array([1,2,3,4,"a","b"])
print(arr.dtype)

<U11


In [3]:
arr=np.array([1,2,3,4])
new=np.float32(arr)
print(new.dtype)

float32


In [4]:
#astype
new.astype(str)

array(['1.0', '2.0', '3.0', '4.0'], dtype='<U32')

In [6]:
#Shape and Reshape
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [9]:
arr=np.array([1,2,3,4],ndmin=4)
print(arr)
print(arr.shape) # 

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [11]:
arr=np.array([[1,2,3,4],[1,2,3,4]],ndmin=4)
print(arr)
print(arr.shape) #

[[[[1 2 3 4]
   [1 2 3 4]]]]
(1, 1, 2, 4)


In [13]:
arr=np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]],ndmin=4)
print(arr)
print(arr.shape) #

[[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]
(1, 1, 3, 4)


In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [21]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(2,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(2,3,2)
one=x.reshape(-1)
print(one)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
#Arithmetic Operations in Numpy Array
arr=np.array([1,2,3,4])
arr=arr+3 #Addition
print(arr)

[4 5 6 7]


In [5]:
arr=np.array([1,2,3,4])
arr1=np.array([1,2,3,4])
arr3=arr+arr1 #Addition
print(arr3)
#Same subraction,Multiplication and Division can be performed

[2 4 6 8]


In [6]:
arr=np.array([1,2,3,4])
arr1=np.array([1,2,3,4])
arr3=np.add(arr,arr1) #Addition
print(arr3)
#Same subraction,Multiplication and Division can be performed

[2 4 6 8]


In [8]:
#2D Array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print("Result")
arr3=np.add(arr,arr1) #Addition
print(arr3)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]
Result
[[ 2  4  6  8]
 [10 12 14 16]]


In [ ]:
#axis=0 works along rows
#axis=1 works along columns