In [2]:
import numpy as np
import random

In [31]:
arr=np.random.rand(3,3) #genrate simple numpy array with 3 rows and 3 columns
print(arr)

[[3.80227561e-01 7.70347899e-01 2.28400243e-01]
 [7.23207961e-01 3.34922501e-01 5.23444321e-05]
 [3.10621316e-01 2.91640859e-01 6.53107699e-01]]


In [10]:
#Now checking their shape and dimenisions
print(np.shape(arr)) #shape() method indicates that how many rows and columns a array have
print(arr.ndim) #tells the dimensions of the array
print(arr.dtype) #tells about the type of data in the array

(3, 3)
2
float64


In [8]:
#Scalar Operations on Numpy array 
print(arr*10) #Simple matrix mutliplication
print("\n",arr+arr) #Addition of two matrix

[[1.39135557 1.08187727 6.85369385]
 [1.22880612 7.5600399  8.2311044 ]
 [6.93574115 9.65997553 7.05270309]]

 [[0.27827111 0.21637545 1.37073877]
 [0.24576122 1.51200798 1.64622088]
 [1.38714823 1.93199511 1.41054062]]


In [9]:
#Creating Arrays
#one of the very simple method of creating an array is that we can pass a list to array method 
l=[1,2,3,4]
arr1=np.array(l)
print(arr1)

[1 2 3 4]


In [14]:
#Creating Multidimensional Array
#When creating the multidimensional array no of elements must be same in all the lists
array_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
#checking dimnension
print("\n",array_2d.ndim)
#checking data type
print("\n",array_2d.dtype)
#checking the shape
print("\n",array_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]

 2

 int32

 (2, 4)


In [17]:
#There are some other methods as well for creating an arrays like
zero_array=np.zeros(12) #creates an array of 12 zero
ones_array=np.ones(12) #creates an array of 12 ones
print(zero_array)
print(ones_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
#Creating Multidimensional Arrays
#2D
zero_2darray=np.zeros((4,2)) #creates an array containing zeros having 4 rows and 2 columns
print(zero_2darray)
print(zero_2darray.shape)
print(zero_2darray.ndim)
print(zero_2darray.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(4, 2)
2
float64


In [22]:
#2D Ones array
one_2darray=np.ones((3,6)) #creates an array containing zeros having 4 rows and 2 columns
print(one_2darray)
print(one_2darray.shape)
print(one_2darray.ndim)
print(one_2darray.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(3, 6)
2
float64


In [27]:
#3D Array
one_3darray=np.ones((3,3,6)) #creates an array containing ones having 3 rows and 6 columns np.ones((3,3,6)) first no 3 means how many arrays 
#3 means no of rows
#6 means no of columns
print(one_3darray)
print(one_3darray.shape)
print(one_3darray.ndim)
print(one_3darray.dtype)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
(3, 3, 6)
3
float64


In [34]:
emparr=np.empty((3,6)) # returns garbage values
#it will return uninitialized garbage values
emparr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
#eye returns identity array
eyearr=np.eye(4)
eyearr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
#arange
#Another method of creating an numpy array is arange method 
arr=np.arange(12) #This simply creates an array of  values 0-11 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
#Data type
arr=np.array([1,2,3,4],dtype=np.float32)
arr1=np.array([1.2,2.9,3.6,4.6],dtype=np.int32)
print(arr)
print(arr1)
print(arr.dtype)
print(arr1.dtype)

[1. 2. 3. 4.]
[1 2 3 4]
float32
int32


In [46]:
#Type Casting
arr=np.array([1,2,3,4])
print(arr)
print("Before Type  Casting",arr.dtype)
arr=arr.astype("float32")
print(arr)
print("After Type  Casting",arr.dtype)

[1 2 3 4]
Before Type  Casting int32
[1. 2. 3. 4.]
After Type  Casting float32


In [48]:
#Type Casting FLoat to Int
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
print("Before Type  Casting",arr.dtype)
arr=arr.astype(np.int32)
print(arr)
print("After Type  Casting",arr.dtype)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
Before Type  Casting float64
[ 3 -1 -2  0 12 10]
After Type  Casting int32


In [54]:
#Strings to float
numeric_strings = np.array(['1.25', '-9.6', '42'])
print(numeric_strings)
print("Before Type  Casting",numeric_strings.dtype)
numeric_strings=numeric_strings.astype(np.float32)
print(numeric_strings)
print("After Type  Casting",numeric_strings.dtype)

['1.25' '-9.6' '42']
Before Type  Casting <U4
[ 1.25 -9.6  42.  ]
After Type  Casting float32


In [56]:
#Another Way
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)
#In this program we have created an array using arange function having dtype as int  and created another array haing dtype as float 
#then pass flaot array to astype method int array it would convert whole array to flaot array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
empty_uint32 = np.empty(8, dtype='u4') #you can also change type by only write code in dtype attribute
print(empty_uint32)

[         0 1072693248          0 1072693248          0 1072693248
          0 1072693248]
