In [ ]:
# PROJECT 1 STUDENT SUBJECT MARKS STATS
#Mean: Calculate the mean score for each subject.
# Median: Find the median score for each subject.
# Variance and Standard Deviation: Determine the variance and standard deviation for each subject to understand the spread of the data.
# Minimum and Maximum: Identify the highest and lowest scores in each subject.
# Correlation: Analyze the correlation between scores in different subjects (e.g., Math vs. Science).
# You can use this dataset to practice using NumPy's statistical functions and get comfortable with basic data manipulation.

In [1]:
import numpy as np

In [2]:
# Load the CSV file
data = np.genfromtxt('student_grades.csv', delimiter=',', skip_header=1)

In [3]:
# Display the loaded data
print(data)

[[ 1. 85. 78. 92. 74. 88.]
 [ 2. 76. 85. 89. 91. 72.]
 [ 3. 90. 92. 94. 89. 95.]
 [ 4. 65. 70. 68. 80. 82.]
 [ 5. 88. 79. 85. 84. 90.]
 [ 6. 95. 88. 91. 92. 87.]
 [ 7. 72. 75. 80. 70. 78.]
 [ 8. 85. 90. 88. 86. 92.]
 [ 9. 78. 82. 79. 83. 76.]
 [10. 82. 85. 87. 88. 84.]]


In [18]:
#Filtering data according to Subjects
Math_Scores=data[:,1]
English_Scores=data[:,2]
Science_Scores=data[:,3]
History_Scores=data[:,4]
Art_Score=data[:,5]

In [27]:
#Calculating mean
print(f"Math Score Mean:\t{np.mean(Math_Scores)}")
print(f"English Score Mean:\t{np.mean(English_Scores)}")
print(f"Science Score Mean:\t{np.mean(Science_Scores)}")
print(f"History Score Mean:\t{np.mean(History_Scores)}")
print(f"Arts Score Mean:\t{np.mean(Art_Score)}")

Math Score Mean:	81.6
English Score Mean:	82.4
Science Score Mean:	85.3
History Score Mean:	83.7
Arts Score Mean:	84.4


In [28]:
#Calculating Median
print(f"Math Score Median:\t{np.median(Math_Scores)}")
print(f"English Score Median:\t{np.median(English_Scores)}")
print(f"Science Score Median:\t{np.median(Science_Scores)}")
print(f"History Score Median:\t{np.median(History_Scores)}")
print(f"Arts Score Median:\t{np.median(Art_Score)}")

Math Score Median:	83.5
English Score Median:	83.5
Science Score Median:	87.5
History Score Median:	85.0
Arts Score Median:	85.5


In [30]:
#Calculating Varience
print(f"Math Score Variance:\t{np.var(Math_Scores)}")
print(f"English Score Variance:\t{np.var(English_Scores)}")
print(f"Science Score Variance:\t{np.var(Science_Scores)}")
print(f"History Score Variance:\t{np.var(History_Scores)}")
print(f"Arts Score Varience:\t{np.var(Art_Score)}")

Math Score Variance:	72.63999999999999
English Score Variance:	43.440000000000005
Science Score Variance:	54.40999999999999
History Score Variance:	47.010000000000005
Arts Score Varience:	49.24000000000001


In [32]:
#Calculating Standard Deviation
print(f"Math Score Standard Deviation:\t{np.std(Math_Scores)}")
print(f"English Score Standard Deviatioo:\t{np.std(English_Scores)}")
print(f"Science Score Standard Deviation:\t{np.std(Science_Scores)}")
print(f"History Score Standard Deviation:\t{np.std(History_Scores)}")
print(f"Arts Score Standard Deviation:\t{np.std(Art_Score)}")

Math Score Standard Deviation:	8.522910301065005
English Score Standard Deviatioo:	6.590902821313633
Science Score Standard Deviation:	7.37631344236401
History Score Standard Deviation:	6.856383886568779
Arts Score Standard Deviation:	7.017121917139534


In [34]:
#Finding Maximum
print(f"Math Score Maximum:\t{np.max(Math_Scores)}")
print(f"English Score Maximum:\t{np.max(English_Scores)}")
print(f"Science Score Maximum:\t{np.max(Science_Scores)}")
print(f"History Score Maximum:\t{np.max(History_Scores)}")
print(f"Arts Score Maximum:\t{np.max(Art_Score)}")

Math Score Maximum:	95.0
English Score Maximum:	92.0
Science Score Maximum:	94.0
History Score Maximum:	92.0
Arts Score Maximum:	95.0


In [35]:
#Finding Minumum
print(f"Math Score Minimum:\t{np.min(Math_Scores)}")
print(f"English Score Minimum:\t{np.min(English_Scores)}")
print(f"Science Score Minimum:\t{np.min(Science_Scores)}")
print(f"History Score Minimum:\t{np.min(History_Scores)}")
print(f"Arts Score Minimum:\t{np.min(Art_Score)}")

Math Score Minimum:	65.0
English Score Minimum:	70.0
Science Score Minimum:	68.0
History Score Minimum:	70.0
Arts Score Minimum:	72.0


In [45]:
#Co Relation B/W Math & Science
math_and_science = data[:, [1, 3]]
correlation_matrix = np.corrcoef(grades, rowvar=False)
# Display the correlation matrix
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[1.         0.7291672  0.82745249 0.49421298 0.66648496]
 [0.7291672  1.         0.77710138 0.73954808 0.40303427]
 [0.82745249 0.77710138 1.         0.41502853 0.44783192]
 [0.49421298 0.73954808 0.41502853 1.         0.15006626]
 [0.66648496 0.40303427 0.44783192 0.15006626 1.        ]]
